#!/bin/sh

echo "🔍 Running pre-commit hook..."

files=$(git diff --cached --name-only)

if [ -z "$files" ]; then
  echo "✅ No files staged for commit."
  exit 0
fi

# Run knip to detect unused files and exports
echo "🕵️ Running knip check..."
pnpm knip || exit 1

echo "🚀 Running lint..."
pnpm run lint || exit 1

echo "✅ Pre-commit checks passed."
exit 0